[package]
name = "stale-urls"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
percent-encoding = "2.3"
regex = "1.11"
terminal_size = "0.4"
xdg = "3.0"

[dev-dependencies]
assert_cmd = "2.2"
tempfile = "3.20"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ["cfg(dylint_lib, values(any()))"]

[[workspace.metadata.dylint.libraries]]
git = "https://github.com/trailofbits/dylint"
pattern = [
    "examples/general",
    "examples/supplementary",
    "examples/restriction/inconsistent_qualification",
    "examples/restriction/misleading_variable_name",
]
